## Aufgabe 2

In [25]:
import numpy as np
import math

list = np.random.randint(10,size=10)
as_array = np.array(list)
print("List: ", as_array)
print("Shape: ", as_array.shape)
print("Type: ", type(as_array))
print("Datentyp der Elemente: ", as_array.dtype)

List:  [1 4 5 4 6 9 3 5 4 0]
Shape:  (10,)
Type:  <class 'numpy.ndarray'>
Datentyp der Elemente:  int64


## Aufgabe 3

In [13]:
print(as_array + 42)
print(as_array - 21)
print(as_array * 2)

[48 49 43 47 46 49 46 42 44 43]
[-15 -14 -20 -16 -17 -14 -17 -21 -19 -20]
[12 14  2 10  8 14  8  0  4  2]


## Aufgabe 4

In [14]:
print(np.mean(as_array))
print(np.median(as_array))
print(np.std(as_array))

3.7
4.0
2.4515301344262523


## Aufgabe 5

In [18]:
mul_dimensional = np.random.randint(10, size=(4,4))
print(mul_dimensional)

[[7 2 5 5]
 [5 4 8 5]
 [5 0 1 6]
 [6 7 8 9]]


In [19]:

print((mul_dimensional[0] + mul_dimensional[1]) * mul_dimensional[-1,-1])

[108  54 117  90]


## Aufgabe 6

In [27]:
first_dimension = 2
reshaped = mul_dimensional.reshape(first_dimension,int(mul_dimensional.size/first_dimension))
print(reshaped)

[[7 2 5 5 5 4 8 5]
 [5 0 1 6 6 7 8 9]]


## Final

In [29]:
final = np.random.randint(10,size=(5,5))
print(final)

[[5 4 4 7 4]
 [6 2 4 7 2]
 [4 2 8 2 8]
 [7 8 4 6 5]
 [1 4 4 8 7]]


In [30]:
total_sum = np.sum(final)
column_sums = np.sum(final, axis=0)
row_sums = np.sum(final, axis=1)

print("Total: ", total_sum)
print("Column Sums: ", column_sums)
print("Row Sums: ", row_sums)

Total:  123
Column Sums:  [23 20 24 30 26]
Row Sums:  [24 21 24 30 24]


In [34]:
print("Min: ", np.min(final), " at [", np.argmin(final),"], Max: ", np.max(final), " at [", np.argmax(final), "]")

Min:  1  at [ 20 ], Max:  8  at [ 12 ]
